spring.application.name=DB_Project

# ============ Server ============
server.port=8081

# ============ DataSource (MySQL) ============
spring.datasource.url=jdbc:mysql://localhost:3307/petdb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=ddon8282**
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============ JPA / Hibernate ============
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect




